# Grunt aliases
---
# Build everything
build:
  - 'build:js'
  - 'build:i18n'

'build-watch':
  - 'shell:composer-install'
  - 'build:js'
  - 'watch'

# Build JavaScript from assets to production
'build:js':
  - 'clean:build-assets-js'
  - 'webpack:buildDev'

# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
  - 'makepot'

# Create a zipped artifact from a fresh build
'artifact':
  - 'shell:composer-install-production'
  - 'update-version'
  - 'build'
  - 'clean:artifact'
  - 'copy:artifact'
  - 'compress:artifact'
  - 'shell:composer-install-dev'

# Default task
default:
  - build

# Get the project ready for release
release:
  - 'build'
