os: linux
language: php
dist: xenial

services:
  - mysql

cache:
  directories:
    - vendor
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

branches:
  only:
    - master
    - trunk
    - /^release\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^feature\/*/
    # Also build tags like 1.1.1 or 1.1 for deployment.
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  fast_finish: true
  include:
    - php: 7.3
      env: WP_VERSION=master PHPUNIT=1
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1 PHPUNIT=1
    - php: 5.6
      env: WP_VERSION=5.8 WP_MULTISITE=1 PHPLINT=1 PHPUNIT=1
      # Use 'trusty' to test against MySQL 5.6, 'xenial' contains 5.7 by default.
      dist: trusty
    - php: 7.4
      env: WP_VERSION=latest PHPLINT=1 PHPUNIT=1
    - php: 8.0
      env: WP_VERSION=latest PHPLINT=1 PHPUNIT=1
    - stage: deploy-to-github-dist
      env: WP_VERSION=latest
      if: tag IS present
      before_install:
        - openssl aes-256-cbc -K $encrypted_b489f7a38f66_key -iv $encrypted_b489f7a38f66_iv -in ./deploy_keys/wpseo_news_deploy.enc -out ./deploy_keys/wpseo_news_deploy -d
        - chmod 600 ./deploy_keys/wpseo_news_deploy
        - eval $(ssh-agent -s)
        - ssh-add ./deploy_keys/wpseo_news_deploy
        - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN
      before_deploy:
        - nvm install 14
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn global add grunt-cli
        - yarn install
        - grunt set-version -new-version=$TRAVIS_TAG
        - grunt update-version
        - grunt artifact
      # If the commit was tagged, create an artifact and push it to the distribution github
      deploy:
        skip_cleanup: true
        provider: script
        script: bash scripts/deploy_to_dist.sh $TRAVIS_TAG wpseo-news
        on:
          tags: true
          repo: $TRAVIS_REPO_SLUG
          all_branches: true
  allow_failures:
    # Allow failures for unstable builds.
    - php: 7.3
      env: WP_VERSION=master PHPUNIT=1

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN

install:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:1} == "8" || $TRAVIS_PHP_VERSION == "nightly" ]]; then
      travis_retry composer install --no-interaction --ignore-platform-reqs
    elif [[ "$PHPUNIT" == "1" || "$PHPLINT" == "1" ]]; then
      travis_retry composer install --no-interaction
    elif [[ "$TRAVIS_BUILD_STAGE_NAME" == "deploy-to-github-dist" ]]; then
      travis_retry composer install --no-dev --no-interaction
    fi

before_script:
  # Careful: The HTTPS version of the following URL is different, therefore we need to use HTTP.
  - |
    if [[ "$WP_VERSION" == "latest" ]]; then
      curl -s http://api.wordpress.org/core/version-check/1.7/ > /tmp/wp-latest.json
      WP_VERSION=$(grep -o '"version":"[^"]*' /tmp/wp-latest.json | sed 's/"version":"//')
    fi
  - PLUGIN_SLUG=$(basename $(pwd))
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish

  # Clone WordPress
  #
  - |
    if [[ "$PHPUNIT" == "1" ]]; then
      git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
    fi

  # Clone WPSEO and its submodule
  #
  - |
    if [[ "$PHPUNIT" == "1" ]]; then
      git clone --depth=1 --branch="trunk" https://github.com/Yoast-dist/wordpress-seo.git $WP_DEVELOP_DIR/src/wp-content/plugins/wordpress-seo
      cd /tmp/wordpress/src/wp-content/plugins/wordpress-seo
      travis_retry composer install --no-dev --no-scripts --no-interaction --ignore-platform-reqs
      cd -
    fi

  # Copy news seo to test dir
  - |
    if [[ "$PHPUNIT" == "1" ]]; then
      cd ..
      cp -r "$PLUGIN_SLUG" "$WP_DEVELOP_DIR/src/wp-content/plugins/$PLUGIN_SLUG"
      cd /tmp/wordpress/
      cp wp-tests-config-sample.php wp-tests-config.php
      sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
      sed -i "s/yourusernamehere/travis/" wp-tests-config.php
      sed -i "s/yourpasswordhere//" wp-tests-config.php
      mysql -e "CREATE DATABASE wordpress_tests;" -uroot
      cd "$WP_DEVELOP_DIR/src/wp-content/plugins/$PLUGIN_SLUG"
      phpenv rehash
    fi

script:
  # JavaScript checks
  - |
    if [[ "$CHECKS" == "1" ]]; then
      travis_fold start "JavaScript.check" && travis_time_start
      npm install -g grunt-cli && npm install --no-optional && grunt check:js
      travis_time_finish && travis_fold end "JavaScript.check"
    fi
  # PHP Linting
  - |
    if [[ "$PHPLINT" == "1" ]]; then
      travis_fold start "PHP.check" && travis_time_start
      composer lint
      travis_time_finish && travis_fold end "PHP.check"
    fi
  # PHP Integration Tests
  - |
    if [[ "$PHPUNIT" == "1" && "$WP_VERSION" != "latest" ]] && [[ "${WP_VERSION:0:3}" == "5.9" || "${WP_VERSION:0:1}" == "6" || "$WP_VERSION" == "master" ]]; then
      travis_fold start "PHP.integration-tests" && travis_time_start
      composer config --unset platform.php &&
      travis_retry composer update yoast/wp-test-utils --with-all-dependencies --no-interaction &&
      vendor/bin/phpunit -c phpunit-integration.xml.dist
      travis_time_finish && travis_fold end "PHP.integration-tests"
    elif [[ "$PHPUNIT" == "1" && ${TRAVIS_PHP_VERSION:0:1} != "8" && $TRAVIS_PHP_VERSION != "nightly" ]]; then
      travis_fold start "PHP.integration-tests" && travis_time_start
      composer integration-test
      travis_time_finish && travis_fold end "PHP.integration-tests"
    elif [[ "$PHPUNIT" == "1" ]] && [[ ${TRAVIS_PHP_VERSION:0:1} == "8" || $TRAVIS_PHP_VERSION == "nightly" ]]; then
      travis_fold start "PHP.integration-tests" && travis_time_start
      travis_retry composer require --dev phpunit/phpunit:"^7.5" --update-with-dependencies --ignore-platform-reqs --no-interaction &&
      composer integration-test
      travis_time_finish && travis_fold end "PHP.integration-tests"
    fi
  # Reset Composer dependencies between the different test setups.
  - git checkout composer.lock composer.json
  - travis_retry composer install --no-interaction
  # PHP Unit Tests
  - |
    if [[ "$PHPUNIT" == "1" && ${TRAVIS_PHP_VERSION:0:1} != "8" && $TRAVIS_PHP_VERSION != "nightly" ]]; then
      travis_fold start "PHP.tests" && travis_time_start
      composer test
      travis_time_finish && travis_fold end "PHP.tests"
    fi
  - |
    if [[ "$PHPUNIT" == "1" ]] && [[ ${TRAVIS_PHP_VERSION:0:1} == "8" || $TRAVIS_PHP_VERSION == "nightly" ]]; then
      travis_fold start "PHP.tests" && travis_time_start
      travis_retry composer update yoast/wp-test-utils --with-dependencies --ignore-platform-reqs --no-interaction &&
      composer test
      travis_time_finish && travis_fold end "PHP.tests"
    fi
