name: Test

on:
  # Run on relevant pushes to select branches and on all relevant pull requests.
  push:
    branches:
      - main
      - trunk
      - 'release/[0-9]+.[0-9]+*'
      - 'hotfix/[0-9]+.[0-9]+*'
      - 'feature/**'
    paths:
      - '**.php' # Includes config/*.php files.
      - '**.xsl'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml.dist'
      - 'phpunit-integration.xml.dist'
      - 'wpml-config.xml'
      - '.github/workflows/test.yml'
      - 'config/scripts/install-wp-tests.sh'
      - 'integration-tests/**'
      - 'tests/**'
  pull_request:
    paths:
      - '**.php' # Includes config/*.php files.
      - '**.xsl'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml.dist'
      - 'phpunit-integration.xml.dist'
      - 'wpml-config.xml'
      - '.github/workflows/test.yml'
      - 'config/scripts/install-wp-tests.sh'
      - 'integration-tests/**'
      - 'tests/**'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['7.4', '8.0', '8.1']
        coverage: [false]

        # Run code coverage only on high/low PHP.
        include:
        - php_version: 7.2
          coverage: true
        - php_version: 8.2
          coverage: true

    name: "Unit Test: PHP ${{ matrix.php_version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: ${{ matrix.coverage == true && 'xdebug' || 'none' }}

      # Download/install YoastSEO via Packagist (YoastDist based) instead of cloning.
      # YoastSEO isn't needed for this workflow anyway and this prevents randomly failing
      # builds due to Git bug "BUG: refs/files-backend.c:2992: initial ref transaction called with existing refs".
      - name: "Composer: use Packagist for YoastSEO and don't install in vendor"
        run: |
          composer config --unset preferred-install
          composer config --unset repositories.wordpress-seo
          composer config --unset extra.installer-paths

      # The PHP platform requirement would prevent updating the test utilities to the appropriate versions.
      # As long as the `composer update` is run selectively to only update the test utils, removing this is fine.
      - name: "Composer: remove the PHP platform requirement"
        run: composer config --unset platform.php

      # Install dependencies and handle caching in one go.
      # - Updates the test utilities to the most appropriate version for the PHP version on which the tests will be run.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          # Force a `composer update` run.
          dependency-versions: "highest"
          # But make it selective.
          composer-options: "yoast/wp-test-utils --with-dependencies"
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Run unit tests
        if: ${{ matrix.coverage == false }}
        run: composer test

      - name: Run the unit tests with code coverage
        if: ${{ matrix.coverage == true }}
        run: composer coverage

      # PHP Coveralls doesn't fully support PHP 8.x yet, so switch the PHP version.
      - name: Switch to PHP 7.4
        if: ${{ success() && matrix.coverage == true && startsWith( matrix.php_version, '8' ) }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      # Global install is used to prevent a conflict with the local composer.lock in PHP 8.0+.
      - name: Install Coveralls
        if: ${{ success() && matrix.coverage == true }}
        run: composer global require php-coveralls/php-coveralls:"^2.5.3" --no-interaction

      - name: Upload coverage results to Coveralls
        if: ${{ success() && matrix.coverage == true }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: unit-php-${{ matrix.php_version }}
        run: php-coveralls -v -x build/logs/clover.xml

  integration-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php_version: '7.2'
            wp_version: '6.1'
            multisite: true
            coverage: true

          - php_version: '7.3'
            wp_version: 'trunk'
            multisite: true
            coverage: false

          - php_version: '7.4'
            wp_version: 'latest'
            multisite: false
            coverage: false

          # WP 5.6 is the earliest version which (sort of) supports PHP 8.0.
          - php_version: '8.0'
            wp_version: '6.1'
            multisite: false
            coverage: false

          # WP 5.9 is the earliest version which (sort of) supports PHP 8.1.
          - php_version: '8.1'
            wp_version: 'latest'
            multisite: true
            coverage: false

          # WP 6.1 is the earliest version which supports PHP 8.2.
          - php_version: '8.2'
            wp_version: '6.2'
            multisite: true
            coverage: true

    name: "Integration Test: PHP ${{ matrix.php_version }} | WP ${{ matrix.wp_version }}${{ matrix.multisite == true && ' (+ ms)' || '' }}"

    # Allow builds to fail on as-of-yet unreleased WordPress versions.
    continue-on-error: ${{ matrix.wp_version == 'trunk' }}

    services:
      mysql:
        # Use MySQL 5.6 for PHP 7.2, use MySQL 5.7 for PHP 7.3 < 7.4, otherwise MySQL 8.0.
        # Also see: https://core.trac.wordpress.org/ticket/52496
        image: mysql:${{ ( matrix.php_version == '7.2' && '5.6' ) || ( matrix.php_version < '7.4' && '5.7' ) || '8.0' }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: ${{ matrix.coverage == true && 'xdebug' || 'none' }}

      # Download/install YoastSEO via Packagist (YoastDist based) instead of cloning.
      # YoastSEO _is_ needed for the integration tests, but feature branches and trunk are deployed
      # to dist on every push anyway and the dist repo already has a pre-prepared vendor_prefixed directory
      # in place, which makes life a lot simpler for this workflow.
      # This will also prevent randomly failing builds due to Git bug
      # "BUG: refs/files-backend.c:2992: initial ref transaction called with existing refs".
      - name: "Composer: use YoastDist for YoastSEO"
        run: composer config --unset repositories.wordpress-seo

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: "Composer: remove the PHP platform requirement"
        run: composer config --unset platform.php

      - name: "Install Composer dependencies"
        uses: ramsey/composer-install@v2
        with:
          # Force a `composer update` run.
          dependency-versions: "highest"
          # But make it selective.
          composer-options: "yoast/wp-test-utils --with-dependencies"
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      # Update YoastSEO as a separate step so the caches will be reasonably stable.
      # This also prevents potentially updating dependencies of YoastSEO due to the above
      # Composer install runs using `--with[-all]-dependencies` for updates.
      - name: Update YoastSEO to the latest version
        run: composer update yoast/wordpress-seo --no-interaction

      - name: Install WP
        shell: bash
        run: config/scripts/install-wp-tests.sh wordpress_test root '' 127.0.0.1:3306 ${{ matrix.wp_version }}

      - name: Run unit tests - single site
        if: ${{ matrix.coverage == false }}
        run: composer integration-test
        env:
          WP_PLUGIN_DIR: "./vendor/yoast"

      - name: Run unit tests - multisite
        if: ${{ matrix.multisite == true && matrix.coverage == false }}
        run: composer integration-test
        env:
          WP_PLUGIN_DIR: "./vendor/yoast"
          WP_MULTISITE: 1

      - name: Run unit tests with code coverage - single site
        if: ${{ matrix.coverage == true }}
        run: composer integration-coverage
        env:
          WP_PLUGIN_DIR: "./vendor/yoast"

      - name: Run unit tests with code coverage - multisite
        if: ${{ matrix.multisite == true && matrix.coverage == true }}
        run: composer integration-coverage -- --coverage-clover build/logs/clover-integration-ms.xml
        env:
          WP_PLUGIN_DIR: "./vendor/yoast"
          WP_MULTISITE: 1

      # PHP Coveralls doesn't fully support PHP 8.x yet, so switch the PHP version.
      - name: Switch to PHP 7.4
        if: ${{ success() && matrix.coverage == true && startsWith( matrix.php_version, '8' ) }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      # Global install is used to prevent a conflict with the local composer.lock in PHP 8.0+.
      - name: Install Coveralls
        if: ${{ success() && matrix.coverage == true }}
        run: composer global require php-coveralls/php-coveralls:"^2.5.3" --no-interaction

      - name: Upload coverage results to Coveralls - single site
        if: ${{ success() && matrix.coverage == true }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: intgr-php-${{ matrix.php_version }}-wp-${{ matrix.wp_version }}
        run: php-coveralls -v -x build/logs/clover-integration.xml

      - name: Upload coverage results to Coveralls - multisite
        if: ${{ success() && matrix.multisite == true && matrix.coverage == true }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: intgr-php-${{ matrix.php_version }}-wp-${{ matrix.wp_version }}-ms
        run: php-coveralls -v -x build/logs/clover-integration-ms.xml

  coveralls-finish:
    needs: [unit-test, integration-test]
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          parallel-finished: true
